import Head from 'next/head';
import { Roboto } from 'next/font/google';
import { Heading, Text } from '@ignite-ui/react';
import { Container, Hero, Preview } from './styles';
import Image from 'next/image';
import previewImage from '../../assets/app-preview.png';
import ClaimUsernameForm from './ClaimUsernameForm';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Ignite Call</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={`${roboto.variable}`}>
        <Container>
          <Hero>
            <Heading size="4xl">Agendamento descomplicado</Heading>
            <Text size="xl">
              Conecte seu calendário e permita que as pessoas marquem
              agendamentos no seu tempo livre.
            </Text>
            <ClaimUsernameForm />
          </Hero>
          <Preview>
            <Image
              src={previewImage}
              height={400}
              quality={100}
              priority
              alt="Calendário simbolizando aplicação em funcionamento"
            />
          </Preview>
        </Container>
      </div>
    </>
  );
}
